version: "3.9"

services:
  servidor-foda:
    container_name: server
    image: server-node
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DB_USERNAME=postgres
      - DB_HOST=db
      - DB=sqlanches
      - DB_PASSWORD=1234
      - DB_PORT=5432
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5439:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=sqlanches
